mybot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  # Position Controllers ---------------------------------------
  bw_left_vc:
    type: effort_controllers/JointVelocityController
    joint: left_wheel_hinge
    pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 0.0}
  bw_right_vc:
    type: effort_controllers/JointVelocityController
    joint: right_wheel_hinge
    pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 0.0}
  leg_left_front_pc:
    type: effort_controllers/JointPositionController
    joint: base_to_left_front_leg
    pid: {p: 200.0, i: 1.00, d: 10.0}
  leg_left_back_pc:
    type: effort_controllers/JointPositionController
    joint: base_to_left_back_leg
    pid: {p: 200.0, i: 1.00, d: 10.0}
#  right_front_leg_pc:
#    type: effort_controllers/JointPositionController
#    joint: base_to_right_front_leg
#    pid: {p: 100.0, i: 0.01, d: 10.0}
#  right_back_leg_pc:
#    type: effort_controllers/JointPositionController
#    joint: base_to_right_back_leg
#    pid: {p: 100.0, i: 0.01, d: 10.0}
  tr_left_front_vc:
    type: effort_controllers/JointVelocityController
    joint: left_front_track_joint
    pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 0.0}
  tr_left_back_vc:
    type: effort_controllers/JointVelocityController
    joint: left_back_track_joint
    pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 0.0}
  tr_right_front_vc:
    type: effort_controllers/JointVelocityController
    joint: right_front_track_joint
    pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 0.0}
  tr_right_back_vc:
    type: effort_controllers/JointVelocityController
    joint: right_back_track_joint
    pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 0.0}
  mw_left_front_vc:
    type: effort_controllers/JointVelocityController
    joint: wheel_to_left_front_leg
    pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 0.0}
  mw_left_back_vc:
    type: effort_controllers/JointVelocityController
    joint: wheel_to_left_back_leg
    pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 0.0}
  mw_right_front_vc:
    type: effort_controllers/JointVelocityController
    joint: wheel_to_right_front_leg
    pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 0.0}
  mw_right_back_vc:
    type: effort_controllers/JointVelocityController
    joint: wheel_to_right_back_leg
    pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 0.0}


